### ISSUE TITLE
Contributing.md file info needs  to be added.

### ISSUE THREAD

**Issue by KalidasVijaybhak** [GDSC-SCTCE/Simple-Web-Project#3]

**Comment by Anubhav-1020** [comment]
Hey @KalidasVijaybhak ...would you pls help me in how to add Contributing.md . I am new to open source. It would really helpful if you assign me this issue..

**Comment by KalidasVijaybhak** [comment]
> Hey @KalidasVijaybhak ...would you pls help me in how to add Contributing.md . I am new to open source. It would really helpful if you assign me this issue..

Contribution.md file is for our team to work on you are assigned with updation of readme.md :)

**Comment by Anubhav-1020** [comment]
Okay got it 👍🏻
