### ISSUE TITLE
Readme needs updation as per hactoberfest criteria

### ISSUE THREAD

**Issue by GDSC-SCTCE** [GDSC-SCTCE/Simple-Web-Project#4]

**Comment by Anubhav-1020** [comment]
Hey @GDSC-SCTCE.. I would like to update Readme.md. Please assign me this issue. I would make a PR once I am done.

**Comment by GDSC-SCTCE** [comment]
Okey Anubhav , You can work on the README.md . I will assign you to this issue 
Deadline : 2-4 OCT 2021

Please update on or before the given timeframe

**Comment by Anubhav-1020** [comment]
Thanks. : )

**Comment by Anubhav-1020** [comment]
Brother... you closed the Issue ? Would me assign me new one ? Or i have to still work upon this ?
