### ISSUE TITLE
Add a nav bar to tribute page

### ISSUE THREAD

**Issue by KalidasVijaybhak** [GDSC-SCTCE/Simple-Web-Project#6]

**Comment by honeykpatel** [comment]
Hey I would like to add this, Can you please assign this to me?

**Comment by GDSC-SCTCE** [comment]
> Hey I would like to add this, Can you please assign this to me?

Yup sure ,please add this feature within two days :)

**Comment by yas-sisodia** [comment]
@KalidasVijaybhak Please allow me to work over this project I can do this

**Comment by KalidasVijaybhak** [comment]
> @KalidasVijaybhak Please allow me to work over this project I can do this

Yup do this .

**Comment by Dcode-k** [comment]
@GDSC-SCTCE Please assign this task to me. I will do it.
