### ISSUE TITLE
Add rules and regulation of event in readme.md 

### ISSUE THREAD

**Issue by KalidasVijaybhak** [GDSC-SCTCE/Simple-Web-Project#9]

**Comment by wasim7raja10** [comment]
I am contributing to this issue.

**Comment by wasim7raja10** [comment]
I have added the rules and regulation. Please let me know if I have to modify it.

**Comment by GDSC-SCTCE** [comment]
> I have added the rules and regulation. Please let me know if I have to modify it.

Thank you @wasim7raja10  for your contribution
